name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '22'
      - name: NPM Install
        run: |
          npm ci
          rm -rf node_modules/@mongodb-js/zstd
          npm i --platform=linux --arch=arm64
      - name: Build
        run: npm run build
      - name: Summarize Lamdba deployment bundle sizes
        run: |
          echo '# Lambda Sizes' >> $GITHUB_STEP_SUMMARY
          echo '|Size|Build Directory|' >> $GITHUB_STEP_SUMMARY
          echo '|-|-|' >> $GITHUB_STEP_SUMMARY
          du -hs $(find build -name 'index.*js' -exec dirname {} \;) | perl -pe 's/^\s*/|/; s/(\s+)/|/; s/$/|/' >> $GITHUB_STEP_SUMMARY
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: build

  deploy:
    name: Deploy to AWS
    needs: build
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev
            url: https://dev.gcn.nasa.gov
          - env: test
            url: https://test.gcn.nasa.gov
          - env: prod
            url: https://gcn.nasa.gov
    environment:
      name: ${{ matrix.env }}
      url: ${{ matrix.url }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '22'
      - name: NPM Install
        run: npm ci
      - name: Download artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          merge-multiple: true
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1
      - name: Deploy
        run: npx arc deploy --prune --production --no-hydrate
